"""initial migration

Revision ID: 35a826f5ff39
Revises: 
Create Date: 2018-08-20 16:21:28.292038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a826f5ff39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imgtag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_name')
    )
    op.create_table('photogroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photogroup_ctime'), 'photogroup', ['ctime'], unique=False)
    op.create_index(op.f('ix_photogroup_name'), 'photogroup', ['name'], unique=True)
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_upload', sa.String(length=128), nullable=True),
    sa.Column('img_title', sa.String(length=128), nullable=True),
    sa.Column('img_context', sa.String(length=200), nullable=True),
    sa.Column('is_top', sa.Boolean(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('is_display', sa.Boolean(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=True),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['theme_id'], ['photogroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_ctime'), 'photo', ['ctime'], unique=False)
    op.create_table('photos_tags',
    sa.Column('img_id', sa.Integer(), nullable=True),
    sa.Column('imgtag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['img_id'], ['photo.id'], ),
    sa.ForeignKeyConstraint(['imgtag_id'], ['imgtag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos_tags')
    op.drop_index(op.f('ix_photo_ctime'), table_name='photo')
    op.drop_table('photo')
    op.drop_index(op.f('ix_photogroup_name'), table_name='photogroup')
    op.drop_index(op.f('ix_photogroup_ctime'), table_name='photogroup')
    op.drop_table('photogroup')
    op.drop_table('imgtag')
    # ### end Alembic commands ###
